version: '3.3'
services:
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: always
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    volumes:
      - .logs/:/app/logs
volumes:
  redis_data: